# NUMPY PRACTICE & TESTING THERE FUNCTION AS WELLL

## Numpy  essestial Functions for DataScience 

   ### M.FAHAD FAROOQ

# How To Install It :

In [43]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# Import Numpy

In [44]:
import numpy as np 

# HOW TO CREATE NUMPY ARRAY 

In [45]:
lst=[1,2,3,4,5]
np.array(lst)


array([1, 2, 3, 4, 5])

In [46]:
lst=[[1,2,3,4],[4,5,6,7],[8,9,10,11]]
np.array(lst)

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# NUMPY 'arange' Func

## LIKE THIS (Start,Stop,Step-Size)

In [47]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# IF WE ONLY WANT EVEN NUMBERS IN ARRAY BY 'arange' func

In [48]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

# IF WE ONLY WANT ODD NUMBERS IN ARRAY BY 'arange' func

In [49]:
np.arange(0,11,3)

array([0, 3, 6, 9])

# CREATE ARRAYS OF ONLY ZEROS ONE OR MORE DIMENSIONAL 

In [50]:
np.zeros(2)

array([0., 0.])

In [51]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [52]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# CREATE ARRAYS OF ONLY ONES ONE OR MORE DIMENSIONAL 

In [53]:
np.ones(3)

array([1., 1., 1.])

In [54]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# NUMPY 'linspace' Func  

## IT WILL CREATE ARRAY WHICH WHICH WILL BE EVENLY DSITRIBUTED  

## LIKE THIS (Start,Stop,Point)

In [55]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

# HOW TO CREATE IDENTITY ARRAY/MATRIX  IN NUMPY

In [56]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# HOW TO USE RANDOM FUNCTION 

## np.random.rand()

## IT WILL GIVE UNIFORMLY DISTRIBUTED ARRAY FROM (0,1)

In [58]:
np.random.rand(5)

array([0.46771413, 0.29119386, 0.78956834, 0.59163461, 0.66681936])

In [59]:
np.random.rand(5,5)

array([[0.15015085, 0.51853556, 0.50750735, 0.354856  , 0.97601604],
       [0.58258633, 0.52058618, 0.83610583, 0.51179221, 0.35394139],
       [0.77436799, 0.02046824, 0.40292043, 0.12981747, 0.31405691],
       [0.82385281, 0.83796319, 0.47440857, 0.45648562, 0.56045129],
       [0.73108711, 0.16916986, 0.51384275, 0.23332903, 0.17416392]])

## np.random.randn()

## IT WILL GIVE STANDARD NORMAL DISTRIBUTED ARRAY CENTRAL AROUND ZERO 

In [60]:
np.random.randn(2,2)

array([[-0.27607552,  0.57445359],
       [-0.6153422 , -1.23802857]])

In [61]:
np.random.randn(4)

array([ 1.38808901,  0.30854396, -0.40762022, -0.52398141])

## np.random.randint()

## IT WILL RANDOMLY GENRATE ARRAY OF RANDOM INTEGER 

### LIKE THIS (Low,High,How many number you want) 

In [62]:
np.random.randint(1,100)

63

In [63]:
np.random.randint(1,100,15)

array([72, 48, 49, 13, 63, 55, 90, 92, 68, 58, 74, 28,  3, 99, 25])

# Built-in Methods

## Testing Some Function Of Numpy

In [64]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
rarr=np.random.randint(0,50,15)
rarr

array([30, 30, 23,  0, 41, 27, 38, 10, 15, 41, 16,  5, 10, 35, 12])

# Reshape

In [80]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# MINIMUM,MAXIMUM VALUE AND THERE INDEX

In [81]:
arr.min()

0

In [82]:
arr.max()

24

In [83]:
arr.argmax()

24

In [84]:
arr.argmin()

0

In [85]:
rarr.min()

0

In [86]:
rarr.max()

41

In [87]:
rarr.argmax()    #maximum number location 

4

# SHAPE

In [75]:
arr.shape

(25,)

In [76]:
rarr.shape

(15,)

In [78]:
t=arr.reshape(5,5)

In [79]:
t.shape

(5, 5)

# DATA TYPE

In [88]:
arr.dtype

dtype('int32')

In [89]:
t.dtype

dtype('int32')

In [90]:
rarr.dtype

dtype('int32')

# OTHER THINGS ARE IN Part 02 !